<#
.SYNOPSIS
    Checks the comment-based help of every exported DnsLathund command.

.DESCRIPTION
    Enforces CONTRACTS §16 and §17: for every exported function, Get-Help
    -Full must show a real synopsis (not the auto-generated syntax line), a
    description, at least three examples that each carry an explanation,
    inputs, outputs, notes, and a description for every parameter except
    the common parameters and -WhatIf/-Confirm.

    While the module skeleton or its public commands are still being
    written, the file reports a skipped test instead of failing.
#>

BeforeDiscovery {
    $script:HelpManifestPath = Join-Path -Path $PSScriptRoot -ChildPath '..\DnsLathund.psd1'
    $script:HelpManifestExists = Test-Path -LiteralPath $script:HelpManifestPath -PathType Leaf
    $script:HelpCommandCases = @()

    if ($script:HelpManifestExists) {
        # Discovery needs the command list to generate one block per command.
        # A broken manifest is reported by the run phase ('imports the module').
        try {
            Import-Module -Name $script:HelpManifestPath -Force -ErrorAction Stop

            $excludedParameters = @([System.Management.Automation.PSCmdlet]::CommonParameters) +
                @([System.Management.Automation.PSCmdlet]::OptionalCommonParameters)

            $script:HelpCommandCases = @(
                foreach ($command in (Get-Command -Module DnsLathund -CommandType Function | Sort-Object -Property Name)) {
                    @{
                        CommandName    = $command.Name
                        ParameterNames = @($command.Parameters.Keys | Where-Object { $excludedParameters -notcontains $_ } | Sort-Object)
                    }
                }
            )
        }
        catch {
            $script:HelpCommandCases = @()
        }
    }
}

BeforeAll {
    $script:HelpImportError = $null
    $manifestPath = Join-Path -Path $PSScriptRoot -ChildPath '..\DnsLathund.psd1'

    if (Test-Path -LiteralPath $manifestPath -PathType Leaf) {
        try {
            Import-Module "$PSScriptRoot\..\DnsLathund.psd1" -Force -ErrorAction Stop
        }
        catch {
            $script:HelpImportError = $_.Exception.Message
        }
    }

    # Help text arrives as arrays of objects with a Text property (or plain
    # strings); this flattens either shape to one trimmed string.
    function Get-HelpText {
        param ($InputObject)

        $parts = @(
            foreach ($item in @($InputObject)) {
                if ($null -eq $item) {
                    continue
                }

                if ($item.PSObject.Properties['Text']) {
                    $item.Text
                }
                else {
                    [string]$item
                }
            }
        )

        ($parts -join '').Trim()
    }
}

Describe 'Comment-based help of exported DnsLathund commands (CONTRACTS §17)' {
    if (-not $script:HelpManifestExists) {
        It 'has exported commands to check' {
            Set-ItResult -Skipped -Because 'DnsLathund.psd1 does not exist yet'
        }
    }
    else {
        It 'imports the module' {
            $script:HelpImportError | Should -BeNullOrEmpty
        }

        if ($script:HelpCommandCases.Count -eq 0) {
            It 'has exported commands to check' {
                Set-ItResult -Skipped -Because 'No exported commands yet'
            }
        }
        else {
            Context '<CommandName>' -ForEach $script:HelpCommandCases {
                BeforeAll {
                    $script:Help = Get-Help -Name $CommandName -Full

                    # Get-Help fills Inputs/Outputs from [OutputType()] and
                    # pipeline parameters when the sections are missing, so
                    # the comment block itself is read as well.
                    $script:CommentHelp = $null
                    $functionAst = (Get-Command -Name $CommandName -Module DnsLathund).ScriptBlock.Ast
                    if ($functionAst -isnot [System.Management.Automation.Language.FunctionDefinitionAst]) {
                        $functionAst = $functionAst.Parent
                    }
                    if ($functionAst -is [System.Management.Automation.Language.FunctionDefinitionAst]) {
                        $script:CommentHelp = $functionAst.GetHelpContent()
                    }
                }

                It 'has a synopsis that is not the auto-generated syntax' {
                    $synopsis = ([string]$script:Help.Synopsis).Trim()
                    $autoGenerated = ($synopsis -match ('^' + [regex]::Escape($CommandName) + '(\s+[\[-]|\s*$)')) -or
                        ($synopsis -match '\[<CommonParameters>\]')

                    $synopsis | Should -Not -BeNullOrEmpty
                    $autoGenerated | Should -BeFalse -Because "the synopsis '$synopsis' looks like the generated syntax, so .SYNOPSIS is missing"
                }

                It 'has a description' {
                    Get-HelpText -InputObject $script:Help.Description | Should -Not -BeNullOrEmpty
                }

                It 'has at least three examples, each with an explanation' {
                    $examples = @()
                    if ($script:Help.PSObject.Properties['Examples'] -and $script:Help.Examples) {
                        $examples = @($script:Help.Examples.Example | Where-Object { $null -ne $_ })
                    }

                    $examples.Count | Should -BeGreaterOrEqual 3

                    for ($index = 0; $index -lt $examples.Count; $index++) {
                        Get-HelpText -InputObject $examples[$index].Remarks |
                            Should -Not -BeNullOrEmpty -Because "example $($index + 1) needs a prose explanation after its code"
                    }
                }

                It 'documents its inputs' {
                    $inputs = ''
                    if ($script:Help.PSObject.Properties['inputTypes'] -and $script:Help.inputTypes) {
                        $inputs = Get-HelpText -InputObject @($script:Help.inputTypes.inputType | ForEach-Object { $_.type.name })
                    }

                    $commentInputs = ''
                    if ($null -ne $script:CommentHelp) {
                        $commentInputs = Get-HelpText -InputObject $script:CommentHelp.Inputs
                    }

                    $inputs | Should -Not -BeNullOrEmpty
                    $commentInputs | Should -Not -BeNullOrEmpty -Because 'the comment-based help needs an .INPUTS section'
                }

                It 'documents its outputs' {
                    $outputs = ''
                    if ($script:Help.PSObject.Properties['returnValues'] -and $script:Help.returnValues) {
                        $outputs = Get-HelpText -InputObject @($script:Help.returnValues.returnValue | ForEach-Object { $_.type.name })
                    }

                    $commentOutputs = ''
                    if ($null -ne $script:CommentHelp) {
                        $commentOutputs = Get-HelpText -InputObject $script:CommentHelp.Outputs
                    }

                    $outputs | Should -Not -BeNullOrEmpty
                    $commentOutputs | Should -Not -BeNullOrEmpty -Because 'the comment-based help needs an .OUTPUTS section; [OutputType()] alone is not enough'
                }

                It 'has notes' {
                    $notes = ''
                    if ($script:Help.PSObject.Properties['alertSet'] -and $script:Help.alertSet) {
                        $notes = Get-HelpText -InputObject @($script:Help.alertSet.alert)
                    }

                    $notes | Should -Not -BeNullOrEmpty
                }

                if ($ParameterNames.Count -gt 0) {
                    It 'documents parameter -<_>' -ForEach $ParameterNames {
                        $parameterName = $_
                        $parameterHelp = $null
                        if ($script:Help.PSObject.Properties['parameters'] -and $script:Help.parameters) {
                            $parameterHelp = @($script:Help.parameters.parameter | Where-Object { $_.name -eq $parameterName }) |
                                Select-Object -First 1
                        }

                        $description = ''
                        if ($null -ne $parameterHelp) {
                            $description = Get-HelpText -InputObject $parameterHelp.description
                        }

                        $description | Should -Not -BeNullOrEmpty -Because ".PARAMETER $parameterName is required"
                    }
                }
            }
        }
    }
}
